name: Data Schema Code Convention Check
on:
  push:
    paths:
      - 'DataSchema.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install ajv-cli for JSON Schema validation
      run: npm install -g ajv-cli

    - name: Validate JSON Schema
      run: ajv validate -s DataSchema.json -d DataSchema.json
