name: JSON Linter

on:
  push:
    branches:
      - main  # або вкажи свою гілку, наприклад, LW11

jobs:
  json_linter_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Start JSON Linter
      run: |
        npm i -g @prantlf/jsonlint
        jsonlint $GITHUB_WORKSPACE/DataSchema.json
