name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  data-processing-software:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show .NET and Node.js versions
        run: |
          echo "=== Data Processing Software Versions ==="
          dotnet --version
          node --version

  database-software:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Database Software Versions
        run: |
          echo "=== Database Software Versions ==="
          mysql --version
          psql --version
